[84] Add groups handling to PiNanas users definition
yscialom/pinanas pull request #110
Opened 2023-05-03 20:55 UTC by yscialom

2023-05-04 16:28 UTC, yscialom commented
testé sur uat :)

2023-05-08 15:12 UTC, glevil requested changes

2023-05-09 15:54 UTC, yscialom commented on src/settings.yaml.sample
> +  # User: { login: string, password: string, email: string, (opt)fullname: string, (opt)groups: list of strings }. Exemple:
Fixed in 06388e6

2023-05-10 16:04 UTC, glevil approved these changes

2023-05-10 17:47 UTC, merged